{"config":{"lang":["en"],"min_search_length":3,"prebuild_index":false,"separator":"[\\s\\-]+"},"docs":[{"location":"","text":"Macro Rendering Error # GitCommandError : Cmd('git') failed due to: exit code(128) cmdline: git rev-list --max-count=5 master -- stderr: 'fatal: bad revision 'master' ' Traceback (most recent call last): File \"/home/ogawa/.local/lib/python3.6/site-packages/mkdocs_macros/plugin.py\", line 341, in render return md_template.render(**page_variables) File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/environment.py\", line 1090, in render self.environment.handle_exception() File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/environment.py\", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/_compat.py\", line 28, in reraise raise value.with_traceback(tb) File \"<template>\", line 81, in top-level template code File \"/home/ogawa/git_work/homepage/main.py\", line 23, in update_info for commit in repo.iter_commits('master', max_count=num): File \"/home/ogawa/.local/lib/python3.6/site-packages/git/objects/commit.py\", line 277, in _iter_from_process_or_stream finalize_process(proc_or_stream) File \"/home/ogawa/.local/lib/python3.6/site-packages/git/util.py\", line 329, in finalize_process proc.wait(**kwargs) File \"/home/ogawa/.local/lib/python3.6/site-packages/git/cmd.py\", line 408, in wait raise GitCommandError(self.args, status, errstr) git.exc.GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git rev-list --max-count=5 master -- stderr: 'fatal: bad revision 'master' '","title":"Home"},{"location":"#macro-rendering-error","text":"GitCommandError : Cmd('git') failed due to: exit code(128) cmdline: git rev-list --max-count=5 master -- stderr: 'fatal: bad revision 'master' ' Traceback (most recent call last): File \"/home/ogawa/.local/lib/python3.6/site-packages/mkdocs_macros/plugin.py\", line 341, in render return md_template.render(**page_variables) File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/environment.py\", line 1090, in render self.environment.handle_exception() File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/environment.py\", line 832, in handle_exception reraise(*rewrite_traceback_stack(source=source)) File \"/home/ogawa/.local/lib/python3.6/site-packages/jinja2/_compat.py\", line 28, in reraise raise value.with_traceback(tb) File \"<template>\", line 81, in top-level template code File \"/home/ogawa/git_work/homepage/main.py\", line 23, in update_info for commit in repo.iter_commits('master', max_count=num): File \"/home/ogawa/.local/lib/python3.6/site-packages/git/objects/commit.py\", line 277, in _iter_from_process_or_stream finalize_process(proc_or_stream) File \"/home/ogawa/.local/lib/python3.6/site-packages/git/util.py\", line 329, in finalize_process proc.wait(**kwargs) File \"/home/ogawa/.local/lib/python3.6/site-packages/git/cmd.py\", line 408, in wait raise GitCommandError(self.args, status, errstr) git.exc.GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git rev-list --max-count=5 master -- stderr: 'fatal: bad revision 'master' '","title":"Macro Rendering Error"}]}